$schema: 'https://moonrepo.dev/schemas/tasks.yml'

tasks:
  test:
    command: 'bun test'
    inputs:
      - 'src/**/*'
      - '*.test.ts'
      - '**/*.test.ts'

  typecheck:
    command:
      - 'tsc'
      - '--noEmit'
      - '--pretty'
    inputs:
      - 'src/**/*'
      - 'tsconfig.json'
      - '/tsconfig.json'

  lint:
    command:
      - 'biome'
      - 'lint'
      - '.'
    inputs:
      - 'src/**/*'
      - '*.test.ts'
      - '**/*.test.ts'
      - '/biome.json'

  format:
    command:
      - 'biome'
      - 'format'
      - '--write'
      - '.'
    inputs:
      - 'src/**/*'
      - '*.test.ts'
      - '**/*.test.ts'
      - '/biome.json'
